const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),test=require("node:test"),ts=require("typescript"),Module=require("node:module");
const root=path.resolve(__dirname,"../.."),cache=new Map(),read=(file)=>fs.readFileSync(path.join(root,file),"utf8"),json=(file)=>JSON.parse(read(file));
function load(relative){const file=path.join(root,relative);if(cache.has(file))return cache.get(file).exports;const output=ts.transpileModule(fs.readFileSync(file,"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}}).outputText;const mod=new Module(file,module);cache.set(file,mod);mod.filename=file;mod.paths=Module._nodeModulePaths(path.dirname(file));const base=mod.require.bind(mod);mod.require=(request)=>{if(request==="server-only")return{};if(request.startsWith(".")){const resolved=path.resolve(path.dirname(file),request);if(request.endsWith(".json"))return base(resolved);return load(path.relative(root,`${resolved}.ts`));}return base(request)};mod._compile(output,file);return mod.exports}
const {CharterSupplyIntakeService}=load("src/lib/charters/intake/service.ts"),{InMemorySupplyIntakeRepository}=load("src/lib/charters/intake/in-memory-repository.ts"),{assertTransition}=load("src/lib/charters/intake/state-machine.ts");
const now=()=>new Date("2026-09-20T12:00:00.000Z");let sequence=0;const id=()=>`00000000-0000-4000-8000-${String(++sequence).padStart(12,"0")}`;
function payload(overrides={}){return{submissionType:"OPERATOR_ONBOARDING",sourceIdentity:{sourceType:"OPERATOR_ONBOARDING",sourceName:"operator",sourceUrl:"https://example.invalid/source"},operator:{name:"<b>DEMO OPERATOR</b>",representativeName:null,phone:"010-1234-5678",email:null,websiteUrl:"https://example.invalid",region:"부산"},boats:[{name:"DEMO BOAT",capacity:6,vesselType:"낚시어선",registrationInfo:null}],ports:[{name:"해제면 용학리 마실선착장",region:"전남",address:null,latitude:34.9,longitude:126.3}],charters:[{title:"DEMO CHARTER",targetSpecies:[{rawName:"참돔"}],price:100000,priceUnit:"1인",departureTime:"05:00",returnTime:"14:00",bookingMethod:"전화",bookingUrl:"https://example.invalid/book"}],schedules:[{date:"2026-10-01",departureTime:"05:00",returnTime:"14:00",capacity:6,remainingSeats:null}],documents:[],...overrides};}
const setup=()=>{const repository=new InMemorySupplyIntakeRepository();return{repository,service:new CharterSupplyIntakeService(repository,now,id)}};

test("creates, fetches and lists a server-validated submission",async()=>{const{service}=setup(),created=await service.create(payload(),"user-1","create-key-001");assert.equal(created.submission.status,"REVIEW_REQUIRED");assert.equal((await service.get(created.submission.id)).id,created.submission.id);assert.equal((await service.list()).length,1);});
test("rejects an invalid submission type",async()=>{const{service}=setup();await assert.rejects(()=>service.create(payload({submissionType:"OFFICIAL_CONNECTOR"}),"user-1","create-key-002"),error=>error.code==="VALIDATION_ERROR");});
test("server validation rejects unsafe URL",async()=>{const{service}=setup(),result=await service.create(payload({sourceIdentity:{sourceType:"OPERATOR_ONBOARDING",sourceName:"x",sourceUrl:"javascript:alert(1)"}}),"user-1","create-key-003");assert.equal(result.submission.status,"VALIDATION_FAILED");});
test("server validation rejects invalid price and capacity",async()=>{const{service}=setup(),input=payload();input.boats[0].capacity=-1;input.charters[0].price=-1;const result=await service.create(input,"user-1","create-key-004");assert.equal(result.submission.validationResult.errors,2);});
test("server validation distinguishes malformed numbers from unknown",async()=>{const{service}=setup(),input=payload();input.charters[0].price="not-a-number";const result=await service.create(input,"user-1","malformed-number-001");assert.equal(result.submission.status,"VALIDATION_FAILED");assert.match(result.submission.validationResult.issues.map((item)=>item.code).join(","),/INVALID_NUMBER/);});
test("unknown numeric values remain null",async()=>{const{service}=setup(),input=payload();input.charters[0].price=null;input.schedules[0].remainingSeats=null;const result=await service.create(input,"user-1","create-key-005");assert.equal(result.submission.normalizedPayload.charters[0].price,null);assert.equal(result.submission.normalizedPayload.schedules[0].remainingSeats,null);});
test("maps exact canonical species without fuzzy fallback",async()=>{const{service}=setup(),result=await service.create(payload(),"user-1","create-key-006");assert.equal(result.submission.normalizedPayload.charters[0].targetSpecies[0].matchType,"EXACT_CANONICAL");const input=payload();input.charters[0].targetSpecies=[{rawName:"참돰"}];const other=await service.create(input,"user-2","create-key-007");assert.equal(other.submission.normalizedPayload.charters[0].targetSpecies[0].matchType,"UNRESOLVED");});
test("keeps user coordinates USER_SUBMITTED",async()=>{const{service}=setup(),result=await service.create(payload(),"user-1","create-key-008");assert.equal(result.submission.normalizedPayload.ports[0].coordinateStatus,"USER_SUBMITTED");});
test("persists MOF candidate without auto approval",async()=>{const{service}=setup(),result=await service.create(payload(),"user-1","create-key-009");assert.equal(result.submission.registrationCrosswalk.status,"CANDIDATE");assert.equal(result.submission.registrationCrosswalk.autoApproved,false);});
test("same idempotency request replays and conflicting reuse fails",async()=>{const{service}=setup(),first=await service.create(payload(),"user-1","create-key-010"),repeat=await service.create(payload(),"user-1","create-key-010");assert.equal(repeat.idempotent,true);assert.equal(repeat.submission.id,first.submission.id);await assert.rejects(()=>service.create(payload({operator:{...payload().operator,name:"different"}}),"user-1","create-key-010"),error=>error.code==="DUPLICATE_SUBMISSION");});
test("same content with another key is a duplicate",async()=>{const{service}=setup();await service.create(payload(),"user-1","create-key-011");await assert.rejects(()=>service.create(payload(),"user-1","create-key-012"),error=>error.code==="DUPLICATE_SUBMISSION");});
test("enforces valid and invalid transitions",()=>{assert.doesNotThrow(()=>assertTransition("DRAFT","SUBMITTED"));assert.throws(()=>assertTransition("DRAFT","APPROVED"),error=>error.code==="INVALID_STATE_TRANSITION");});
test("unapproved submission cannot create a promotion",async()=>{const{service,repository}=setup();await service.create(payload(),"user-1","create-key-013");assert.equal(repository.promotions.length,0);});
test("approval creates one non-production promotion candidate",async()=>{const{service,repository}=setup(),created=await service.create(payload(),"user-1","create-key-014");const approved=await service.review(created.submission.id,"admin-1","APPROVE","근거 확인 완료");assert.equal(approved.status,"APPROVED");assert.equal(repository.promotions.length,1);assert.equal(repository.promotions[0].productionActivated,false);});
test("rejection records immutable review and no promotion",async()=>{const{service,repository}=setup(),created=await service.create(payload(),"user-1","create-key-015");const rejected=await service.review(created.submission.id,"admin-1","REJECT","근거 부족");assert.equal(rejected.status,"REJECTED");assert.equal(repository.reviews.length,1);assert.equal(repository.promotions.length,0);});
test("request changes uses VALIDATION_FAILED metadata state",async()=>{const{service}=setup(),created=await service.create(payload(),"user-1","create-key-016");assert.equal((await service.review(created.submission.id,"admin-1","REQUEST_CHANGES","자료 보완 필요")).status,"VALIDATION_FAILED");});
test("sanitizes unsafe plain text while preserving immutable raw payload",async()=>{const{service}=setup(),result=await service.create(payload(),"user-1","create-key-017");assert.equal(result.submission.normalizedPayload.operator.name,"bDEMO OPERATOR/b");assert.equal(result.submission.rawPayload.operator.name,"<b>DEMO OPERATOR</b>");});
test("migration enables RLS, revokes browser access and preserves source snapshots",()=>{const sql=read("supabase/migrations/20260920103020_charter_supply_intake_backend_v1.sql");for(const table of ["charter_supply_submissions","charter_supply_reviews","charter_supply_promotion_candidates","charter_supply_audit_logs"])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));assert.match(sql,/revoke all .* anon, authenticated/s);assert.match(sql,/immutable_submission_source/);});
test("API surface is bounded, authenticated and uses standard errors",()=>{const server=read("src/lib/charters/intake/server.ts"),types=read("src/lib/charters/intake/types.ts");assert.match(server,/MAX_REQUEST_BYTES = 262_144/);assert.match(server,/auth\.getUser\(token\)/);assert.match(server,/charter_role==="charter_admin"/);for(const code of ["VALIDATION_ERROR","INVALID_STATE_TRANSITION","SUBMISSION_NOT_FOUND","AUTH_REQUIRED","DUPLICATE_SUBMISSION","INTERNAL_ERROR"])assert.match(types,new RegExp(code));});
test("admin and submission routes exist while production registry stays empty",()=>{for(const file of ["src/app/api/charters/supply/submissions/route.ts","src/app/api/charters/supply/submissions/[id]/route.ts","src/app/api/charters/supply/submissions/[id]/validate/route.ts","src/app/api/charters/supply/submissions/[id]/review/route.ts","src/app/charters/admin/submissions/page.tsx","src/app/charters/admin/submissions/[id]/page.tsx"])assert.equal(fs.existsSync(path.join(root,file)),true);assert.match(read("src/lib/charters/registry.ts"),/operators: \[\], boats: \[\], ports: \[\], charters: \[\], schedules: \[\]/);});
test("report records auth limitation and no remote apply",()=>{const report=json("reports/charters/supply-intake-backend-v1.json");assert.equal(report.decision,"SUPPLY_INTAKE_BACKEND_V1_READY_WITH_AUTH_LIMITATIONS");assert.equal(report.database.remoteApplied,false);assert.equal(report.promotion.productionActivation,0);});
test("reservations and Fishing Journey remain outside backend changes",()=>{assert.doesNotMatch(read("src/app/reservations/page.tsx"),/supply\/submissions/);assert.match(read("tests/fishing-spots/fishing-journey-integration-v1.test.cjs"),/journey/i);});
