const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const dir=path.resolve(__dirname,'../../../supabase/migrations/drafts/staging-ready'),rpc=fs.readFileSync(path.join(dir,'005_fish_observation_rpc.sql'),'utf8'),workers=fs.readFileSync(path.join(dir,'006_fish_worker_claim_rpcs.sql'),'utf8'),all=rpc+'\n'+workers;
const hotfixDir=path.resolve(__dirname,'../../../supabase/migrations/drafts/staging-hotfix'),revocationHotfix=fs.readFileSync(path.join(hotfixDir,'20260817_fix_revocation_same_target_claim.sql'),'utf8'),operationHotfix=fs.readFileSync(path.join(hotfixDir,'20260817_fix_role_operation_claim_timeout.sql'),'utf8');
test('mutation functions are definer functions with fixed search paths and PUBLIC revoke',()=>{for(const name of ['confirm_fish_observation','claim_fish_media_cleanup_jobs','claim_fish_role_session_revocation_jobs','claim_fish_role_change_operation','claim_fish_role_approval_reconciliation']){assert.match(all,new RegExp(`create function public\\.${name}\\(`,'i'));assert.match(all,new RegExp(`revoke all on function public\\.${name}\\(`,'i'))}assert.equal((all.match(/security definer/gi)||[]).length>=5,true);assert.doesNotMatch(all,/set search_path\s*=\s*public\s*(?:,|as)/i)});
test('confirmation prevents actor forgery and locks idempotency and observation rows',()=>{assert.match(rpc,/p_verified_by is distinct from v_caller/i);assert.match(rpc,/where idempotency_key=btrim\(p_idempotency_key\) for update/i);assert.match(rpc,/where id=p_observation_id for update/i);assert.match(rpc,/selected_species_is_not_an_ai_candidate/i);assert.match(rpc,/observation_already_confirmed/i)});
test('confirmation uses the active role projection and blocks crawler execution',()=>{assert.match(rpc,/v_role text:=public\.current_fish_role\(\)/i);assert.match(rpc,/crawler_confirmation_forbidden/i);assert.doesNotMatch(rpc,/v_role text:=coalesce\(auth\.jwt/i)});
test('confirmation treats NULL roles as ordinary owners and rejects stale or malformed role claims',()=>{assert.match(rpc,/v_claimed_role text:=coalesce\(auth\.jwt\(\)->'app_metadata'->>'fish_role',''\)/i);assert.match(rpc,/v_claimed_role<>'' and v_role is null/i);assert.match(rpc,/v_role is null and v_observation\.user_id<>v_caller/i);assert.match(rpc,/v_has_current and v_role is distinct from 'fish_admin'/i);assert.equal((rpc.match(/v_role is distinct from 'fish_admin'/gi)||[]).length,3);assert.doesNotMatch(rpc,/v_role not in \('fish_admin','fish_reviewer'\) and v_observation/i);assert.doesNotMatch(rpc,/v_has_current and v_role<>'fish_admin'/i);assert.doesNotMatch(rpc,/if v_role<>'fish_admin'/i)});

function roleMatrixAllows({role=null,claimedRole='',ownsObservation=false,verificationType='user_confirmed',hasCurrent=false}){if(claimedRole!==''&&role===null)return false;if(role==='fish_crawler')return false;if(role==='fish_reviewer'&&verificationType!=='expert_confirmed')return false;if(role===null&&verificationType!=='user_confirmed')return false;if(role!==null&&!['fish_admin','fish_reviewer'].includes(role))return false;if(role===null&&!ownsObservation)return false;if(hasCurrent&&role!=='fish_admin')return false;return true}
for(const scenario of[
  ['NULL role owner user confirmation',true,{ownsObservation:true}],
  ['NULL role foreign observation',false,{ownsObservation:false}],
  ['NULL role expert confirmation',false,{ownsObservation:true,verificationType:'expert_confirmed'}],
  ['reviewer foreign expert confirmation',true,{role:'fish_reviewer',claimedRole:'fish_reviewer',verificationType:'expert_confirmed'}],
  ['reviewer override',false,{role:'fish_reviewer',claimedRole:'fish_reviewer',verificationType:'expert_confirmed',hasCurrent:true}],
  ['admin intended override',true,{role:'fish_admin',claimedRole:'fish_admin',verificationType:'expert_confirmed',hasCurrent:true}],
  ['crawler confirmation',false,{role:'fish_crawler',claimedRole:'fish_crawler'}],
  ['malformed role claim',false,{role:null,claimedRole:'fish_root',ownsObservation:true}]
])test(`authorization matrix: ${scenario[0]}`,()=>assert.equal(roleMatrixAllows(scenario[2]),scenario[1]));
test('admin correction serializes and rebuilds old and new collection aggregates',()=>{assert.match(rpc,/pg_advisory_xact_lock\(hashtextextended/i);assert.match(rpc,/array\[v_previous_species_id,p_selected_species_id\]/i);assert.match(rpc,/set is_current=false,superseded_at=now\(\)/i);assert.match(rpc,/discovery_count=excluded\.discovery_count/i);assert.match(rpc,/override_observation_confirmation/i)});
test('distinct rebuild loops use a PostgreSQL-valid deterministic UUID order',()=>{const loops=rpc.match(/select distinct species_id from unnest\(array\[v_previous_species_id,p_selected_species_id\]\) as s\(species_id\)\s+where species_id is not null order by species_id/gi)||[];assert.equal(loops.length,2);assert.doesNotMatch(rpc,/select distinct species_id[^;]+order by species_id::text/i)});
test('confirmation execute is denied to public and anon before authenticated grant',()=>{assert.match(rpc,/revoke all on function public\.confirm_fish_observation\(uuid,uuid,text,uuid,text\) from public,anon,authenticated/i);assert.match(rpc,/grant execute on function public\.confirm_fish_observation\(uuid,uuid,text,uuid,text\) to authenticated/i)});
test('worker claims are bounded, leased, skip locked and service-only',()=>{assert.equal((workers.match(/for update(?: of \w+)? skip locked/gi)||[]).length>=3,true);assert.equal((workers.match(/p_limit < 1 or p_limit > 100/gi)||[]).length>=3,true);assert.match(workers,/auth\.jwt\(\)->>'role'.*service_role/i);assert.doesNotMatch(workers,/grant execute[^;]+to authenticated/i);assert.equal((workers.match(/grant execute[^;]+to service_role/gi)||[]).length,4);assert.equal((workers.match(/from public,anon,authenticated/gi)||[]).length,4)});
test('expired worker leases can be reclaimed with bounded lease durations',()=>{assert.match(workers,/status = 'leased' and lease_expires_at < now\(\)/i);assert.match(workers,/status = 'claimed' and lease_expires_at < now\(\)/i);assert.match(workers,/status='locked' and lease_expires_at < now\(\)/i);assert.equal((workers.match(/p_lease_seconds < 10 or p_lease_seconds > 900/gi)||[]).length,4)});
test('revocation claims serialize each target and prioritize critical work',()=>{assert.match(workers,/partition by target_user_id/i);assert.match(workers,/target_rank=1/i);assert.match(workers,/order by \(j\.priority='critical'\) desc/i)});
test('revocation claims exclude targets with another active lease',()=>{assert.match(workers,/not exists\s*\([\s\S]*active\.target_user_id\s*=\s*candidate\.target_user_id/i);assert.match(workers,/active\.job_id\s*<>\s*candidate\.job_id/i);assert.match(workers,/active\.status\s*=\s*'claimed'/i);assert.match(workers,/active\.lease_token is not null/i);assert.match(workers,/active\.lease_expires_at\s*>\s*now\(\)/i)});
test('non-claimable role operations use a non-retryable SQLSTATE',()=>{assert.match(workers,/errcode='55000', message='operation_not_claimable'/i);assert.doesNotMatch(workers,/errcode='40001', message='operation_not_claimable'/i)});
test('worker hotfixes replace only the intended functions and preserve service-only ACLs',()=>{for(const [sql,name,signature] of[[revocationHotfix,'claim_fish_role_session_revocation_jobs','integer,integer'],[operationHotfix,'claim_fish_role_change_operation','uuid,integer']]){assert.match(sql,new RegExp(`create or replace function public\\.${name}\\(`,'i'));assert.match(sql,/security definer/i);assert.match(sql,/set search_path=pg_catalog,public,auth,extensions,pg_temp/i);assert.match(sql,new RegExp(`revoke all on function public\\.${name}\\(${signature}\\) from public,anon,authenticated`,'i'));assert.match(sql,new RegExp(`grant execute on function public\\.${name}\\(${signature}\\) to service_role`,'i'));assert.doesNotMatch(sql,/\b(?:create|alter|drop)\s+(?:table|index|policy)\b/i)}});
test('approval reconciliation uses a durable lease instead of a transient row lock',()=>{assert.match(workers,/add column reconciliation_lease_token uuid/i);assert.match(workers,/fish_role_approvals_reconciliation_lease_pair_chk/i);assert.match(workers,/fish_role_approvals_reconciliation_claim_idx/i);assert.match(workers,/set reconciliation_lease_token=gen_random_uuid\(\)/i);assert.match(workers,/reconciliation_lease_expires_at < now\(\)/i)});
