const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const file=path.resolve(__dirname,'../../../supabase/migrations/drafts/staging-ready/004_fish_rls_and_roles.sql'),sql=fs.readFileSync(file,'utf8');
const sensitive=['fish_observations','fish_observation_private_locations','fish_identification_attempts','fish_observation_verifications','fish_collections','fish_observation_confirmations','fish_media_upload_sessions','fish_media_cleanup_jobs','fish_role_assignments','fish_role_change_operations','fish_role_idempotency_records','fish_role_session_revocation_jobs','fish_role_approvals'];
test('every sensitive table is in the RLS enable list',()=>{for(const name of sensitive)assert.match(sql,new RegExp(`'${name}'`))});
test('public and owner reads are narrow',()=>{assert.match(sql,/fish_species_public_read[\s\S]*publish_status='published'[\s\S]*fact_review_status='approved'/i);assert.match(sql,/fish_media_public_read[\s\S]*privacy='public'[\s\S]*exif_status='stripped'/i);assert.match(sql,/fish_observations_owner_select[\s\S]*user_id=auth\.uid\(\)/i);assert.match(sql,/fish_observations_owner_insert[\s\S]*species_id is null[\s\S]*verification_status='pending'/i)});
test('server-only tables receive no browser write policy',()=>{for(const name of ['fish_observation_confirmations','fish_media_cleanup_jobs','fish_role_change_operations','fish_role_approvals'])assert.doesNotMatch(sql,new RegExp(`create policy[^;]+on public\\.${name}[^;]+for (?:insert|update|delete|all)`,'i'))});
test('browser default ACLs are reset before narrow grants',()=>{assert.match(sql,/revoke all privileges on table public\.%I from anon,authenticated/i);assert.doesNotMatch(sql,/grant\s+(?:all|delete|truncate)\b[^;]*\bto\s+(?:anon|authenticated)/i)});
test('observation writes cannot set verification or moderation fields',()=>{assert.match(sql,/grant insert\(user_id,captured_at,region,fishing_spot_id,marine_place_id,length_cm,weight_g,notes,visibility,location_privacy,is_personal_record,is_anonymous\)/i);assert.match(sql,/grant update\(captured_at,region,fishing_spot_id,marine_place_id,length_cm,weight_g,notes,visibility,location_privacy,is_personal_record,is_anonymous\)/i);assert.doesNotMatch(sql,/grant (?:insert|update)\([^)]*(?:species_id|verification_status|moderation_status|deletion_status)[^)]*\)/i)});
test('role helpers require a matching active projection and deny public or anon execute',()=>{assert.match(sql,/current_fish_role\(\)[\s\S]*security definer[\s\S]*from public\.fish_role_assignments/i);assert.match(sql,/a\.user_id=auth\.uid\(\)[\s\S]*a\.status='active'[\s\S]*app_metadata[\s\S]*a\.identity_type/i);assert.match(sql,/revoke all on function public\.current_fish_role\(\) from public,anon,authenticated/i);assert.doesNotMatch(sql,/user_metadata/i)});
