import type { MarketListing, MarketListingDraftInput, MarketListingStatus } from "../types";
export const MARKET_ERROR_CODES=["VALIDATION_ERROR","AUTH_REQUIRED","FORBIDDEN","LISTING_NOT_FOUND","INVALID_STATE_TRANSITION","DUPLICATE_SUBMISSION","PAYLOAD_TOO_LARGE","UNSUPPORTED_MEDIA","RATE_LIMITED","INTERNAL_ERROR"] as const;
export type MarketErrorCode=typeof MARKET_ERROR_CODES[number]; export type ModerationStatus="REVIEW_REQUIRED"|"APPROVED"|"REJECTED"|"CHANGES_REQUESTED"|"HIDDEN"; export type ReviewAction="APPROVE"|"REJECT"|"REQUEST_CHANGES"|"HIDE";
export type StoredMarketListing={listing:MarketListing;moderationStatus:ModerationStatus;idempotencyKey:string;contentHash:string;rawPayload:unknown;normalizedPayload:MarketListingDraftInput;validationResult:{errors:string[];warnings:string[];prohibitedFlags:string[]};submittedAt:string;activatedAt:string|null;reservedAt:string|null;soldAt:string|null};
export type MarketReview={id:string;listingId:string;reviewerId:string;action:ReviewAction;reason:string;createdAt:string};
export type MarketAudit={listingId:string;actorId:string|null;eventType:"DRAFT_CREATED"|"LISTING_SUBMITTED"|"LISTING_VALIDATED"|"REVIEW_RECORDED"|"LISTING_APPROVED"|"LISTING_REJECTED"|"CHANGES_REQUESTED"|"LISTING_ACTIVATED"|"LISTING_RESERVED"|"LISTING_SOLD"|"LISTING_HIDDEN"|"IMAGE_UPLOAD_INTENT_CREATED";fromStatus:MarketListingStatus|null;toStatus:MarketListingStatus|null;details:Record<string,unknown>;createdAt:string};
export type MarketImageRecord={id:string;listingId:string;sellerId:string;objectPath:string;originalFilename:string;mimeType:string;byteSize:number;width:number|null;height:number|null;order:number;exposureStatus:"STAGING"|"APPROVED"|"HIDDEN";createdAt:string};
export interface MarketRepository{find(id:string):Promise<StoredMarketListing|null>;findByIdempotency(seller:string,key:string):Promise<StoredMarketListing|null>;findByContentHash(seller:string,hash:string):Promise<StoredMarketListing|null>;list(limit:number):Promise<StoredMarketListing[]>;listBySeller(seller:string,limit:number):Promise<StoredMarketListing[]>;listPublic(limit:number):Promise<StoredMarketListing[]>;create(value:StoredMarketListing):Promise<StoredMarketListing>;update(value:StoredMarketListing):Promise<StoredMarketListing>;appendReview(value:MarketReview):Promise<void>;appendAudit(value:MarketAudit):Promise<void>;countImages(listingId:string):Promise<number>;listImages(listingId:string):Promise<MarketImageRecord[]>;appendImage(value:MarketImageRecord):Promise<void>}
export class MarketBackendError extends Error{constructor(readonly code:MarketErrorCode,readonly status:number){super(code)}}
