import type { SupabaseClient } from "@supabase/supabase-js";
import type { IntakeAuditEvent, IntakeReviewRecord, PromotionCandidateRecord, StoredSupplySubmission, SupplyIntakeRepository } from "./types";

const fromRow = (row: Record<string, unknown>): StoredSupplySubmission => ({ id:String(row.id),submittedBy:String(row.submitted_by),idempotencyKey:String(row.idempotency_key),contentHash:String(row.content_hash),status:row.status as StoredSupplySubmission["status"],rawPayload:row.raw_payload,normalizedPayload:row.normalized_payload as StoredSupplySubmission["normalizedPayload"],validationResult:row.validation_result as StoredSupplySubmission["validationResult"],registrationCrosswalk:row.registration_crosswalk as StoredSupplySubmission["registrationCrosswalk"],promotionReadiness:row.promotion_readiness as StoredSupplySubmission["promotionReadiness"],submittedAt:String(row.submitted_at),updatedAt:String(row.updated_at),approvedAt:row.approved_at?String(row.approved_at):null,rejectedAt:row.rejected_at?String(row.rejected_at):null,reviewNotes:row.review_notes?String(row.review_notes):null });
const row = (value: StoredSupplySubmission) => ({id:value.id,submission_type:value.normalizedPayload.submissionType,status:value.status,submitted_by:value.submittedBy,idempotency_key:value.idempotencyKey,content_hash:value.contentHash,source_identity:value.normalizedPayload.sourceIdentity,raw_payload:value.rawPayload,normalized_payload:value.normalizedPayload,validation_result:value.validationResult,registration_crosswalk:value.registrationCrosswalk,promotion_readiness:value.promotionReadiness,review_notes:value.reviewNotes,submitted_at:value.submittedAt,approved_at:value.approvedAt,rejected_at:value.rejectedAt,updated_at:value.updatedAt});
const checked = <T>(data:T|null,error:{message:string}|null):T => {if(error||data===null)throw new Error("PERSISTENCE_FAILED");return data;};

export class SupabaseSupplyIntakeRepository implements SupplyIntakeRepository {
  constructor(private readonly client: SupabaseClient) {}
  async find(id:string){const {data,error}=await this.client.from("charter_supply_submissions").select("*").eq("id",id).maybeSingle();return data?fromRow(data):error?checked(data,error):null;}
  async findByIdempotency(user:string,key:string){const {data,error}=await this.client.from("charter_supply_submissions").select("*").eq("submitted_by",user).eq("idempotency_key",key).maybeSingle();return data?fromRow(data):error?checked(data,error):null;}
  async findByContentHash(user:string,hash:string){const {data,error}=await this.client.from("charter_supply_submissions").select("*").eq("submitted_by",user).eq("content_hash",hash).maybeSingle();return data?fromRow(data):error?checked(data,error):null;}
  async list(limit:number){const {data,error}=await this.client.from("charter_supply_submissions").select("*").order("submitted_at",{ascending:false}).limit(limit);return checked(data,error).map(fromRow);}
  async create(value:StoredSupplySubmission){const {data,error}=await this.client.from("charter_supply_submissions").insert(row(value)).select("*").single();return fromRow(checked(data,error));}
  async update(value:StoredSupplySubmission){const patch=row(value);delete (patch as Partial<typeof patch>).raw_payload;delete (patch as Partial<typeof patch>).submitted_by;delete (patch as Partial<typeof patch>).idempotency_key;delete (patch as Partial<typeof patch>).content_hash;const {data,error}=await this.client.from("charter_supply_submissions").update(patch).eq("id",value.id).select("*").single();return fromRow(checked(data,error));}
  async appendReview(value:IntakeReviewRecord){const {error}=await this.client.from("charter_supply_reviews").insert({id:value.id,submission_id:value.submissionId,reviewer_id:value.reviewerId,action:value.action,reason:value.reason,review_snapshot:value,created_at:value.createdAt});if(error)throw new Error("PERSISTENCE_FAILED");}
  async appendAudit(value:IntakeAuditEvent){const {error}=await this.client.from("charter_supply_audit_logs").insert({submission_id:value.submissionId,actor_id:value.actorId,event_type:value.eventType,from_status:value.fromStatus,to_status:value.toStatus,details:value.details,created_at:value.createdAt});if(error)throw new Error("PERSISTENCE_FAILED");}
  async savePromotionCandidate(value:PromotionCandidateRecord){const {error}=await this.client.from("charter_supply_promotion_candidates").insert({submission_id:value.submissionId,candidate_payload:value.candidatePayload,content_hash:value.contentHash,production_activated:false,created_by:value.createdBy,created_at:value.createdAt});if(error&&error.code!=="23505")throw new Error("PERSISTENCE_FAILED");}
}
