"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, CheckCircle2, ImagePlus, ShieldCheck, Trash2 } from "lucide-react";
import { categoryLabels, conditionLabels, priceTypeLabels, transactionLabels } from "@/lib/market/route-helpers";
import { MARKET_CATEGORIES, MARKET_CONDITIONS, MARKET_PRICE_TYPES, MARKET_TRANSACTION_METHODS, type MarketImageInput, type MarketListingDraftInput } from "@/lib/market/types";
import { MAX_MARKET_IMAGES, validateMarketImage, validateMarketListingDraft } from "@/lib/market/validation";
import { createClient } from "@/lib/supabase/client";

const steps = ["카테고리", "기본정보", "가격", "상태", "지역", "거래방식", "이미지", "설명", "검토"] as const;
type Preview = MarketImageInput & { id: string; url: string; file: File };
type OwnListing = { listing: { id: string; title: string; status: string }; moderationStatus: string; normalizedPayload: MarketListingDraftInput };
type FormState = { category:string; subcategory:string; title:string; priceType:string; price:string; condition:string; province:string; district:string; description:string; contactType:string; contactDestination:string };
const initial: FormState = { category:"", subcategory:"", title:"", priceType:"FIXED", price:"", condition:"", province:"", district:"", description:"", contactType:"INQUIRY_PREPARED", contactDestination:"" };

export function MarketListingForm() {
  const [step,setStep]=useState(0); const [form,setForm]=useState(initial); const [methods,setMethods]=useState<string[]>([]); const [images,setImages]=useState<Preview[]>([]);
  const [errors,setErrors]=useState<string[]>([]); const [warnings,setWarnings]=useState<string[]>([]); const [savedId,setSavedId]=useState<string|null>(null); const previewRef=useRef<Preview[]>([]);
  const [submitResult,setSubmitResult]=useState<{listingId:string;status:string;moderationStatus:string}|null>(null);const [submitError,setSubmitError]=useState<string|null>(null);const idempotencyKey=useRef<string|null>(null);
  const [ownListings,setOwnListings]=useState<OwnListing[]>([]);const [editId,setEditId]=useState<string|null>(null);const [existingImages,setExistingImages]=useState<MarketImageInput[]>([]);const [busy,setBusy]=useState(false);const [ownMessage,setOwnMessage]=useState("");
  useEffect(()=>{previewRef.current=images},[images]); useEffect(()=>()=>previewRef.current.forEach((image)=>URL.revokeObjectURL(image.url)),[]);
  const set=(name:keyof FormState,value:string)=>{setForm((current)=>({...current,[name]:value}));setSavedId(null);idempotencyKey.current=null};
  const toggleMethod=(value:string)=>{setMethods((current)=>current.includes(value)?current.filter((item)=>item!==value):[...current,value]);setSavedId(null);idempotencyKey.current=null};
  const price=useMemo(()=>form.priceType==="FREE"?0:form.priceType==="INQUIRY"||!form.price.trim()?null:Number(form.price.replaceAll(",","")),[form.price,form.priceType]);
  const draft=()=>({title:form.title,description:form.description,category:form.category,subcategory:form.subcategory||null,price,priceType:form.priceType,condition:form.condition,province:form.province,district:form.district||null,transactionMethods:methods,images:[...existingImages,...images.map(({name,type,size,order})=>({name,type,size,order}))],contactType:form.contactType,contactDestination:form.contactDestination||null});
  const save=()=>{const result=validateMarketListingDraft(draft());setErrors(result.errors);setWarnings(result.warnings);if(!result.valid){setSavedId(null);return;}const id=`market-local-${crypto.randomUUID()}`;localStorage.setItem(`blue-marina:${id}`,JSON.stringify({id,status:"SUBMITTED",moderationStatus:"REVIEW_REQUIRED",currency:"KRW",sourceType:"USER_SUBMITTED",verificationStatus:"UNVERIFIED",productionVisible:false,createdAt:new Date().toISOString(),listing:result.sanitized}));setSavedId(id);};
  const loadMine=async()=>{
    const client=createClient();const token=(await client?.auth.getSession())?.data.session?.access_token;
    if(!token){setOwnListings([]);setOwnMessage("로그인 후 본인 제출 내역을 확인할 수 있습니다.");return}
    try{const response=await fetch("/api/market/listings?scope=mine",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const body=await response.json() as {listings?:OwnListing[];code?:string};if(!response.ok){setOwnListings([]);setOwnMessage(body.code??"조회 실패");return}setOwnListings(body.listings??[]);setOwnMessage("")}catch{setOwnMessage("네트워크 문제로 본인 내역을 확인하지 못했습니다.")}
  };
  useEffect(()=>{void loadMine()},[]);
  const loadForEdit=async(id:string)=>{
    const client=createClient();const token=(await client?.auth.getSession())?.data.session?.access_token;
    if(!token){setOwnMessage("로그인 후 본인 글을 수정할 수 있습니다.");return}
    try{const response=await fetch(`/api/market/listings/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});const body=await response.json() as {record?:OwnListing;code?:string};if(!response.ok||!body.record){setOwnMessage(body.code??"조회 실패");return}const input=body.record.normalizedPayload;setEditId(id);setExistingImages(input.images??[]);setImages([]);setForm({category:input.category,subcategory:input.subcategory??"",title:input.title,priceType:input.priceType,price:input.price==null?"":String(input.price),condition:input.condition,province:input.province,district:input.district??"",description:input.description,contactType:input.contactType,contactDestination:input.contactDestination??""});setMethods(input.transactionMethods);setStep(8);setSubmitResult({listingId:id,status:body.record.listing.status,moderationStatus:body.record.moderationStatus});setOwnMessage("본인 판매글을 불러왔습니다. 검토 대기 중인 글만 수정할 수 있습니다.")}catch{setOwnMessage("네트워크 문제로 글을 불러오지 못했습니다.")}
  };
  const submit=async()=>{
    if(busy)return;setBusy(true);setSubmitError(null);
    try{
      const result=validateMarketListingDraft(draft());setErrors(result.errors);setWarnings(result.warnings);if(!result.valid)return;
      const client=createClient();const token=(await client?.auth.getSession())?.data.session?.access_token;
      if(!client||!token){setSubmitError("로그인과 활성화된 Market backend가 필요합니다.");return}
      idempotencyKey.current??=`market-${crypto.randomUUID()}`;
      const response=await fetch(editId?`/api/market/listings/${encodeURIComponent(editId)}`:"/api/market/listings",{method:editId?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...(!editId?{"Idempotency-Key":idempotencyKey.current}:{})},body:JSON.stringify(result.sanitized),cache:"no-store"});
      const body=await response.json() as {listingId?:string;status?:string;moderationStatus?:string;record?:OwnListing;code?:string};
      const listingId=editId??body.listingId;if(!response.ok||!listingId){setSubmitError(body.code??"INTERNAL_ERROR");return}
      setEditId(listingId);
      for(const image of images){
        const intentResponse=await fetch(`/api/market/listings/${encodeURIComponent(listingId)}/images/upload-intent`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({filename:image.name,mimeType:image.type,byteSize:image.size,order:image.order}),cache:"no-store"});
        const intent=await intentResponse.json() as {path?:string;token?:string;code?:string};
        if(!intentResponse.ok||!intent.path||!intent.token){setSubmitError(`판매글은 비공개로 저장됐지만 이미지 준비에 실패했습니다: ${intent.code??"INTERNAL_ERROR"}`);await loadMine();return}
        const uploaded=await client.storage.from("market-listing-staging").uploadToSignedUrl(intent.path,intent.token,image.file,{contentType:image.type,upsert:false});
        if(uploaded.error){setSubmitError("판매글은 비공개로 저장됐지만 이미지 업로드에 실패했습니다. 관리자 승인 전까지 공개되지 않습니다.");await loadMine();return}
      }
      setExistingImages(result.sanitized.images);setImages([]);
      setSubmitResult({listingId,status:body.record?.listing.status??body.status??"SUBMITTED",moderationStatus:body.record?.moderationStatus??body.moderationStatus??"REVIEW_REQUIRED"});
      await loadMine();
    }catch{setSubmitError("네트워크 문제로 제출을 완료하지 못했습니다. 본인 내역을 확인해 주세요.")}finally{setBusy(false)}
  };
  const addImages=(files:FileList|null)=>{if(!files)return;const next:Preview[]=[];const fileErrors:string[]=[];for(const file of Array.from(files)){if(existingImages.length+images.length+next.length>=MAX_MARKET_IMAGES){fileErrors.push(`이미지는 최대 ${MAX_MARKET_IMAGES}장입니다.`);break;}const invalid=validateMarketImage(file);if(invalid.length){fileErrors.push(`${file.name}: ${invalid.join(" ")}`);continue;}next.push({id:crypto.randomUUID(),name:file.name,type:file.type,size:file.size,order:existingImages.length+images.length+next.length,url:URL.createObjectURL(file),file});}setImages((current)=>[...current,...next]);setErrors(fileErrors);setSavedId(null);idempotencyKey.current=null;};
  const removeImage=(id:string)=>{setImages((current)=>current.filter((image)=>{if(image.id===id)URL.revokeObjectURL(image.url);return image.id!==id;}).map((image,order)=>({...image,order:existingImages.length+order})));idempotencyKey.current=null;};
  return <section className="mx-auto max-w-5xl py-5 sm:py-10">
    <Link href="/market" className="inline-flex min-h-11 items-center gap-2 text-sm font-black text-[#AEE8EF]"><ArrowLeft size={17}/>마켓으로</Link>
    <div className="mt-4 rounded-[30px] border border-[#1F3A50] bg-[linear-gradient(135deg,#071827,#0C2B3C)] p-6 sm:p-9"><p className="text-xs font-black tracking-[.2em] text-[#79C9D6]">LOCAL LISTING STAGING</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">판매글 검토 초안</h1><p className="mt-4 max-w-3xl text-sm font-semibold leading-7 text-[#B8CBDD]">초안은 이 브라우저에 저장할 수 있습니다. 로그인과 마켓 백엔드가 활성화된 경우에만 검토용 서버 제출이 가능합니다. 관리자 승인 전 운영 노출, 판매자 인증, 거래 완료 또는 결제 처리는 수행하지 않습니다.</p><Link href="/account/login?returnTo=%2Fmarket%2Fnew" className="mt-4 inline-flex min-h-11 items-center rounded-full border border-[#79C9D6]/50 px-4 text-sm font-bold text-[#AEE8EF]">가입·로그인 후 제출하기</Link></div>
    <ol className="mt-6 grid grid-cols-3 gap-2 sm:grid-cols-5 lg:grid-cols-9">{steps.map((label,index)=><li key={label}><button type="button" onClick={()=>setStep(index)} className={`min-h-11 w-full rounded-xl px-2 text-[11px] font-black ${step===index?"bg-[#2E8BFF] text-white":"border border-[#29465D] bg-[#071827] text-[#AFC1D4]"}`}>{index+1}. {label}</button></li>)}</ol>
    <div className="mt-5 rounded-[28px] border border-[#1F3A50] bg-[#071827] p-5 sm:p-8"><h2 className="text-xl font-black">{steps[step]}</h2>
      {step===0?<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{MARKET_CATEGORIES.map((value)=><button key={value} type="button" onClick={()=>set("category",value)} className={`min-h-12 rounded-xl border px-4 text-left text-sm font-black ${form.category===value?"border-[#79C9D6] bg-[#123A4D]":"border-[#29465D] bg-[#050F19]"}`}>{categoryLabels[value]}</button>)}<label className="grid gap-2 text-sm font-bold sm:col-span-2 lg:col-span-3">세부 분류 (선택)<input value={form.subcategory} onChange={(event)=>set("subcategory",event.target.value)} className="control" maxLength={60}/></label></div>:null}
      {step===1?<div className="mt-5"><label className="grid gap-2 text-sm font-bold">상품명<input value={form.title} onChange={(event)=>set("title",event.target.value)} placeholder="4~80자" className="control" maxLength={80}/></label></div>:null}
      {step===2?<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">가격 유형<select value={form.priceType} onChange={(event)=>set("priceType",event.target.value)} className="control">{MARKET_PRICE_TYPES.map((value)=><option key={value} value={value}>{priceTypeLabels[value]}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">가격 (KRW)<input value={form.price} onChange={(event)=>set("price",event.target.value)} inputMode="numeric" placeholder={form.priceType==="INQUIRY"?"비워 둠":"숫자"} disabled={form.priceType==="FREE"||form.priceType==="INQUIRY"} className="control"/></label><p className="text-sm text-[#9FB3C8] sm:col-span-2">확인되지 않은 가격은 0원으로 바꾸지 않습니다. 가격 문의는 금액을 저장하지 않습니다.</p></div>:null}
      {step===3?<div className="mt-5 grid gap-3 sm:grid-cols-2">{MARKET_CONDITIONS.map((value)=><button key={value} type="button" onClick={()=>set("condition",value)} className={`min-h-12 rounded-xl border px-4 text-left text-sm font-black ${form.condition===value?"border-[#79C9D6] bg-[#123A4D]":"border-[#29465D] bg-[#050F19]"}`}>{conditionLabels[value]}</button>)}</div>:null}
      {step===4?<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">시·도<input value={form.province} onChange={(event)=>set("province",event.target.value)} placeholder="예: 부산광역시" className="control"/></label><label className="grid gap-2 text-sm font-bold">시·군·구 (선택)<input value={form.district} onChange={(event)=>set("district",event.target.value)} placeholder="예: 영도구" className="control"/></label><p className="text-sm text-[#9FB3C8] sm:col-span-2">정확한 주소와 좌표는 공개하지 않습니다.</p></div>:null}
      {step===5?<div className="mt-5"><div className="grid gap-3 sm:grid-cols-2">{MARKET_TRANSACTION_METHODS.map((value)=><label key={value} className="flex min-h-12 items-center gap-3 rounded-xl border border-[#29465D] bg-[#050F19] px-4 text-sm font-black"><input type="checkbox" checked={methods.includes(value)} onChange={()=>toggleMethod(value)} className="h-5 w-5"/>{transactionLabels[value]}</label>)}</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">문의 방식<select value={form.contactType} onChange={(event)=>set("contactType",event.target.value)} className="control"><option value="INQUIRY_PREPARED">문의 준비</option><option value="PHONE">전화</option><option value="EMAIL">이메일</option><option value="EXTERNAL_LINK">외부 링크</option></select></label><label className="grid gap-2 text-sm font-bold">문의 정보 (선택)<input value={form.contactDestination} onChange={(event)=>set("contactDestination",event.target.value)} placeholder="전화·이메일 또는 https://" className="control"/></label></div></div>:null}
      {step===6?<div className="mt-5"><label className="inline-flex min-h-12 cursor-pointer items-center gap-2 rounded-full border border-[#79C9D6]/50 px-5 text-sm font-black text-[#AEE8EF]"><ImagePlus size={18}/>이미지 선택<input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={(event)=>addImages(event.target.files)}/></label><p className="mt-3 text-sm text-[#9FB3C8]">JPEG·PNG·WebP, 장당 최대 8 MiB, 최대 {MAX_MARKET_IMAGES}장. 선택 즉시는 로컬 미리보기이며 서버 제출 시에만 비공개 staging 버킷으로 업로드합니다. 업로드 실패 시 판매글은 비공개로 남습니다.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{images.map((image)=><div key={image.id} className="min-w-0 overflow-hidden rounded-xl border border-[#29465D] bg-[#050F19]"><div className="aspect-square bg-cover bg-center" style={{backgroundImage:`url(${image.url})`}}/><div className="flex items-center gap-2 p-2"><span className="min-w-0 flex-1 truncate text-xs">{image.name}</span><button type="button" onClick={()=>removeImage(image.id)} aria-label={`${image.name} 삭제`} className="flex h-9 w-9 shrink-0 items-center justify-center"><Trash2 size={15}/></button></div></div>)}</div></div>:null}
      {step===7?<label className="mt-5 grid gap-2 text-sm font-bold">상품 설명<textarea value={form.description} onChange={(event)=>set("description",event.target.value)} placeholder="상태, 구성품, 사용 이력과 확인이 필요한 내용을 20~3000자로 적어주세요." className="min-h-48 rounded-[18px] border border-[#1F3A50] bg-[#050F19] p-4 text-sm leading-7 text-white outline-none focus:border-[#2E8BFF]" maxLength={3000}/></label>:null}
      {step===8?<div className="mt-5 space-y-4"><div className="grid gap-3 sm:grid-cols-2">{[["카테고리",categoryLabels[form.category as keyof typeof categoryLabels]??"미선택"],["상품명",form.title||"미입력"],["가격",form.priceType==="INQUIRY"?"가격 문의":form.priceType==="FREE"?"무료 나눔":form.price||"미입력"],["상태",conditionLabels[form.condition as keyof typeof conditionLabels]??"미선택"],["지역",`${form.province} ${form.district}`.trim()||"미입력"],["이미지",`${existingImages.length+images.length}장`]].map(([label,value])=><div key={label} className="min-w-0 rounded-xl bg-[#0B2235] p-4"><p className="text-xs font-black text-[#79C9D6]">{label}</p><p className="mt-1 break-words text-sm font-bold">{value}</p></div>)}</div><div className="flex gap-3 rounded-xl border border-amber-300/25 bg-amber-300/8 p-4 text-sm font-semibold leading-6 text-amber-50"><ShieldCheck className="mt-0.5 shrink-0" size={18}/><p>금지품목 규칙과 입력값을 서버에서도 다시 검사합니다. 관리자 승인 전에는 운영 마켓에 표시되지 않습니다.</p></div><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={save} className="min-h-12 rounded-xl border border-[#79C9D6]/50 px-5 text-sm font-black">로컬 초안 저장</button><button type="button" disabled={busy} onClick={()=>void submit()} className="min-h-12 rounded-xl bg-[#2E8BFF] px-5 text-sm font-black disabled:opacity-50">{busy?"처리 중":editId?"본인 글 수정 저장":"판매글 제출"}</button></div></div>:null}
      {errors.length?<div className="mt-5 rounded-xl border border-rose-300/25 bg-rose-300/8 p-4"><p className="font-black text-rose-100">저장할 수 없습니다</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-rose-100/85">{errors.map((error)=><li key={error}>{error}</li>)}</ul></div>:null}
      {warnings.length?<ul className="mt-4 list-disc rounded-xl bg-amber-300/8 p-4 pl-9 text-sm text-amber-50">{warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul>:null}
      {savedId?<div className="mt-5 rounded-xl border border-emerald-300/25 bg-emerald-300/8 p-4 text-sm font-semibold leading-6 text-emerald-50"><CheckCircle2 className="mr-2 inline" size={18}/><strong>로컬 검토 대기 저장됨</strong><br/>ID: <span className="break-all">{savedId}</span><br/>상태는 SUBMITTED / REVIEW_REQUIRED이며 운영 마켓에 표시되지 않습니다.</div>:null}
      {submitResult?<div className="mt-5 rounded-xl border border-emerald-300/25 bg-emerald-300/8 p-4 text-sm font-semibold leading-6 text-emerald-50"><CheckCircle2 className="mr-2 inline" size={18}/><strong>판매글 검토 대기</strong><br/>ID: <span className="break-all">{submitResult.listingId}</span><br/>상태: {submitResult.status} / {submitResult.moderationStatus}. 관리자 승인 전에는 공개되지 않습니다.</div>:null}{submitError?<p role="alert" className="mt-5 break-words rounded-xl bg-rose-300/10 p-4 text-sm font-bold text-rose-100">처리 실패: {submitError}</p>:null}
      <div className="mt-7 flex flex-wrap justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep((value)=>Math.max(0,value-1))} className="min-h-11 rounded-full border border-[#29465D] px-5 text-sm font-black disabled:opacity-30">이전</button><button type="button" disabled={step===steps.length-1} onClick={()=>setStep((value)=>Math.min(steps.length-1,value+1))} className="min-h-11 rounded-full bg-[#2E8BFF] px-5 text-sm font-black disabled:opacity-30">다음</button></div>
    </div>
    <section className="mt-8 rounded-[28px] border border-[#1F3A50] bg-[#071827] p-5 sm:p-8" aria-label="내 판매글">
      <h2 className="text-xl font-black">내 판매글</h2><p className="mt-2 text-sm text-[#9FB3C8]">로그인한 본인만 검토 대기 글을 조회하고 수정할 수 있습니다. 제출만으로 공개되지 않습니다.</p>
      <button type="button" onClick={()=>void loadMine()} className="mt-4 min-h-11 rounded-full border border-[#79C9D6]/50 px-5 text-sm font-bold">내역 새로고침</button>
      {ownMessage?<p role="status" className="mt-3 text-sm text-[#B8CBDD]">{ownMessage}</p>:null}
      <ul className="mt-4 space-y-3">{ownListings.map((row)=><li key={row.listing.id} className="rounded-xl border border-[#29465D] p-4"><p className="break-words font-bold">{row.listing.title}</p><p className="mt-1 text-xs text-[#9FB3C8]">{row.listing.status} / {row.moderationStatus}</p><button type="button" onClick={()=>void loadForEdit(row.listing.id)} className="mt-3 min-h-11 rounded-full border border-[#79C9D6]/50 px-4 text-sm font-bold">본인 글 불러오기</button></li>)}</ul>
    </section>
  </section>;
}
