export type VerificationStatus = "VERIFIED" | "SOURCE_BACKED" | "UNVERIFIED" | "UNKNOWN";
export type AvailabilityStatus = "AVAILABLE" | "FULL" | "INQUIRY_REQUIRED" | "EXTERNAL_BOOKING" | "UNKNOWN";
export type CharterPrice = { amount: number | null; currency: "KRW"; unit: "PER_PERSON" | "PER_BOAT" | "FROM" | "INQUIRY"; sourceFreshness: "LIVE" | "RECENT" | "STATIC" | "UNKNOWN" };
export type Charter = { id: string; operatorId: string; boatId: string | null; departurePortId: string | null; title: string; description: string | null; targetSpeciesIds: string[]; tripType: string; price: CharterPrice; capacity: number | null; bookingMethod: "PHONE" | "INQUIRY" | "EXTERNAL" | "UNKNOWN"; status: AvailabilityStatus; sourceRefs: string[]; verificationStatus: VerificationStatus };
export type CharterDataset = { schemaVersion: 1; datasetKind: "PRODUCTION" | "DEMO"; operators: Array<{ id: string; name: string; region: string; phone: string | null; websiteUrl: string | null; bookingUrl: string | null; verificationStatus: VerificationStatus; sourceRefs: string[] }>; boats: Array<{ id: string; operatorId: string; name: string; capacity: number | null; verificationStatus: VerificationStatus }>; ports: Array<{ id: string; name: string; region: string; latitude: number | null; longitude: number | null; coordinateStatus: VerificationStatus; sourceRefs: string[] }>; charters: Charter[]; schedules: Array<{ id: string; charterId: string; date: string | null; departureTime: string | null; returnTime: string | null; capacity: number | null; remainingSeats: number | null; availabilityStatus: AvailabilityStatus; verificationStatus: VerificationStatus }> };

// Production records remain empty until an authoritative operator source is ingested.
export const productionCharterDataset: CharterDataset = { schemaVersion: 1, datasetKind: "PRODUCTION", operators: [], boats: [], ports: [], charters: [], schedules: [] };
export function getCharter(id: string | undefined) { return id ? productionCharterDataset.charters.find((item) => item.id === id) ?? null : null; }
export function safeExternalUrl(value: string | null | undefined) { try { const url = value ? new URL(value) : null; return url && ["http:", "https:"].includes(url.protocol) ? url.toString() : null; } catch { return null; } }
export function charterPriceLabel(price: CharterPrice) { return price.amount === null ? "가격 문의" : `${price.amount.toLocaleString("ko-KR")}원`; }
export function charterAvailabilityLabel(status: AvailabilityStatus) { return status === "UNKNOWN" ? "예약 가능 여부 확인 필요" : status === "INQUIRY_REQUIRED" ? "문의 필요" : status === "EXTERNAL_BOOKING" ? "공식 예약사이트 확인" : status === "FULL" ? "마감" : "예약 가능"; }
