const assert = require("node:assert/strict"); const test = require("node:test"); const { load } = require("./_load.cjs");
const { FishRoleSessionRevocationWorker } = load("src/domain/fish-authorization/worker/fish-role-session-revocation-worker.ts");
const { FakeFishRoleRevocationClock } = load("src/domain/fish-authorization/testing/fake-fish-role-revocation-clock.ts");
const { FakeFishRoleRevocationWorkerLock } = load("src/domain/fish-authorization/testing/fake-fish-role-revocation-worker-lock.ts");
const { fishRoleRevocationJob, InMemoryFishRoleRevocationQueue, InMemoryFishRoleRevocationState, InMemoryFishRoleRevocationAuditSink } = load("src/domain/fish-authorization/testing/fish-role-revocation-job-fixtures.ts");
function fixture(overrides = {}) { const clock = new FakeFishRoleRevocationClock(); const queue = new InMemoryFishRoleRevocationQueue([fishRoleRevocationJob(overrides.job)]); const state = new InMemoryFishRoleRevocationState(); state.operations.set("operation-1", { operationId: "operation-1", targetUserId: "user-1", status: "session_revocation_pending", sessionRevocationStatus: "pending", version: 1 }); state.projections.set("user-1", { targetUserId: "user-1", role: null, status: "inactive", version: 2 }); const audit = new InMemoryFishRoleRevocationAuditSink(); const revoker = { calls: 0, async revokeAllSessions() { this.calls += 1; }, async markRevocationPending() {} }; const worker = new FishRoleSessionRevocationWorker({ queue, operationRepository: state, projectionReader: state, sessionRevoker: revoker, lock: new FakeFishRoleRevocationWorkerLock(), audit, clock }); return { clock, queue, state, audit, revoker, worker }; }
test("role revocation completes provider, operation, queue, and sanitized audit", async () => { const f = fixture(); const result = await f.worker.run({ batchSize: 10, workerId: "w1", maxRuntimeMs: 10_000 }); assert.equal(result.completed, 1); assert.equal(f.revoker.calls, 1); assert.equal(f.state.operations.get("operation-1").status, "completed"); assert.equal(f.queue.jobs.get("job-1").status, "completed"); assert.equal(JSON.stringify(f.audit.events).includes("token"), false); });
test("admin and emergency jobs are critical and reviewer revoke succeeds", async () => { const f = fixture({ job: { revocationType: "admin_role_changed", priority: "critical" } }); assert.equal((await f.queue.previewCandidates(1, f.clock.now()))[0].priority, "critical"); assert.equal((await f.worker.run({ batchSize: 1, workerId: "w", maxRuntimeMs: 10_000 })).completed, 1); const reviewer = fixture({ job: { revocationType: "reviewer_role_revoked" } }); assert.equal((await reviewer.worker.run({ batchSize: 1, workerId: "w", maxRuntimeMs: 10_000 })).completed, 1); });
test("completed operation is idempotent and never calls provider again", async () => { const f = fixture(); Object.assign(f.state.operations.get("operation-1"), { status: "completed", sessionRevocationStatus: "revoked" }); const result = await f.worker.run({ batchSize: 1, workerId: "w", maxRuntimeMs: 10_000 }); assert.equal(result.completed, 1); assert.equal(f.revoker.calls, 0); });
module.exports = { fixture };
