export const FISH_MEDIA_ERROR_CODES = [
  "UPLOAD_NOT_FOUND", "UPLOAD_EXPIRED", "INVALID_MIME", "MAGIC_BYTE_MISMATCH", "IMAGE_DECODE_FAILED",
  "IMAGE_TOO_LARGE", "PIXEL_LIMIT_EXCEEDED", "EXIF_PROCESSING_FAILED", "HASH_MISMATCH",
  "OBSERVATION_NOT_OWNED", "MEDIA_ALREADY_FINALIZED", "MEDIA_DELETE_PENDING", "STORAGE_DELETE_FAILED",
  "PUBLICATION_NOT_ALLOWED", "CLEANUP_RETRY_EXHAUSTED", "ARBITRARY_STORAGE_PATH",
] as const;

export type FishMediaErrorCode = (typeof FISH_MEDIA_ERROR_CODES)[number];

export const RETRYABLE_FISH_MEDIA_ERROR_CODES: readonly FishMediaErrorCode[] = [
  "STORAGE_DELETE_FAILED", "EXIF_PROCESSING_FAILED", "IMAGE_DECODE_FAILED",
];

export function isRetryableFishMediaError(code: FishMediaErrorCode) {
  return RETRYABLE_FISH_MEDIA_ERROR_CODES.includes(code);
}
