"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ImagePlus, ShieldCheck, Trash2 } from "lucide-react";
import { communityPostTypeLabels } from "@/lib/community/route-helpers";
import { COMMUNITY_POST_TYPES, type CommunityImageInput, type CommunityPostDraft } from "@/lib/community/types";
import { MAX_COMMUNITY_IMAGES, validateCommunityImage, validateCommunityPostDraft } from "@/lib/community/validation";

type Option={id:string;label:string};type Catalog={species:Option[];fishingSpots:Option[];charters:Option[];marketListings:Option[]};
type Preview=CommunityImageInput&{id:string;url:string};
const steps=["글 유형","제목","본문","지역","사진","관련 어종","관련 정보","검토","제출"] as const;
const emptyLinks={species:[] as string[],fishingSpots:[] as string[],charters:[] as string[],marketListings:[] as string[]};

export function CommunityPostForm({catalog}:{catalog:Catalog}){
  const[step,setStep]=useState(0),[type,setType]=useState("GENERAL"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[province,setProvince]=useState(""),[district,setDistrict]=useState("");
  const[images,setImages]=useState<Preview[]>([]),[links,setLinks]=useState(emptyLinks),[errors,setErrors]=useState<string[]>([]),[warnings,setWarnings]=useState<string[]>([]),[savedId,setSavedId]=useState<string|null>(null);const previews=useRef<Preview[]>([]);
  useEffect(()=>{previews.current=images},[images]);useEffect(()=>()=>previews.current.forEach(image=>URL.revokeObjectURL(image.url)),[]);
  const allowed=useMemo(()=>({speciesIds:new Set(catalog.species.map(x=>x.id)),fishingSpotIds:new Set(catalog.fishingSpots.map(x=>x.id)),charterIds:new Set(catalog.charters.map(x=>x.id)),marketListingIds:new Set(catalog.marketListings.map(x=>x.id))}),[catalog]);
  const draft=():CommunityPostDraft=>({type,title,body,province,district:district||null,images:images.map(({name,type,size,order})=>({name,type,size,order})),linkedSpeciesIds:links.species,linkedFishingSpotIds:links.fishingSpots,linkedCharterIds:links.charters,linkedMarketListingIds:links.marketListings});
  const addLink=(key:keyof typeof links,value:string)=>{if(value)setLinks(current=>({...current,[key]:current[key].includes(value)?current[key]:[...current[key],value]}))};
  const removeLink=(key:keyof typeof links,value:string)=>setLinks(current=>({...current,[key]:current[key].filter(id=>id!==value)}));
  const addImages=(files:FileList|null)=>{if(!files)return;const next:Preview[]=[],issues:string[]=[];for(const file of Array.from(files)){if(images.length+next.length>=MAX_COMMUNITY_IMAGES){issues.push("이미지는 최대 10장입니다.");break}const invalid=validateCommunityImage(file);if(invalid.length){issues.push(`${file.name}: ${invalid.join(" ")}`);continue}next.push({id:crypto.randomUUID(),name:file.name,type:file.type,size:file.size,order:images.length+next.length,url:URL.createObjectURL(file)})}setImages(current=>[...current,...next]);setErrors(issues);setSavedId(null)};
  const removeImage=(id:string)=>setImages(current=>current.filter(image=>{if(image.id===id)URL.revokeObjectURL(image.url);return image.id!==id}).map((image,order)=>({...image,order})));
  const submit=()=>{const result=validateCommunityPostDraft(draft(),allowed);setErrors(result.errors);setWarnings(result.warnings);if(!result.valid){setSavedId(null);return}const id=`community-local-${crypto.randomUUID()}`;localStorage.setItem(`blue-marina:${id}`,JSON.stringify({id,status:"SUBMITTED",moderationStatus:"REVIEW_REQUIRED",sourceType:"USER_SUBMITTED",productionVisible:false,createdAt:new Date().toISOString(),post:result.sanitized,safetyFlags:result.safetyFlags}));setSavedId(id)};
  const picker=(label:string,key:keyof typeof links,options:Option[])=><div><label className="grid gap-2 text-sm font-bold">{label}<select defaultValue="" onChange={event=>{addLink(key,event.target.value);event.currentTarget.value=""}} className="min-h-11 rounded-xl border border-[#29465D] bg-[#050F19] px-3"><option value="">{options.length?"명시적으로 선택":"연결 가능한 production 항목 없음"}</option>{options.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></label><div className="mt-2 flex flex-wrap gap-2">{links[key].map(id=><button type="button" key={id} onClick={()=>removeLink(key,id)} className="min-h-11 max-w-full break-all rounded-full border border-[#79C9D6]/40 px-3 text-xs font-black">{id} ×</button>)}</div></div>;
  return <section className="mx-auto max-w-4xl py-5 sm:py-10"><Link href="/community" className="inline-flex min-h-11 items-center gap-2 text-sm font-black text-[#AEE8EF]"><ArrowLeft size={17}/>커뮤니티</Link><div className="mt-4 rounded-[28px] border border-[#1F3A50] bg-[#071827] p-5 sm:p-8"><p className="text-xs font-black tracking-[.2em] text-[#79C9D6]">LOCAL / STAGING</p><h1 className="mt-3 text-3xl font-black">커뮤니티 글 작성</h1><p className="mt-3 text-sm font-semibold leading-6 text-[#9FB3C8]">이 작성 흐름은 로컬 검토용입니다. 저장해도 운영 피드에 게시되거나 서버로 업로드되지 않습니다.</p><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{steps.map((label,index)=><button key={label} type="button" onClick={()=>setStep(index)} className={`min-h-11 shrink-0 rounded-full px-4 text-xs font-black ${index===step?"bg-[#2E8BFF] text-white":"bg-[#0B2235] text-[#9FB3C8]"}`}>{index+1}. {label}</button>)}</div>
    <div className="mt-6 min-w-0">
      {step===0?<div className="grid gap-3 sm:grid-cols-2">{COMMUNITY_POST_TYPES.map(value=><button type="button" key={value} onClick={()=>setType(value)} className={`min-h-12 rounded-xl border px-4 text-left text-sm font-black ${type===value?"border-[#2E8BFF] bg-[#2E8BFF]/15":"border-[#29465D] bg-[#050F19]"}`}>{communityPostTypeLabels[value]}</button>)}</div>:null}
      {step===1?<label className="grid gap-2 text-sm font-bold">제목<input value={title} onChange={event=>setTitle(event.target.value)} maxLength={100} className="min-h-12 rounded-xl border border-[#29465D] bg-[#050F19] px-4" placeholder="4~100자"/></label>:null}
      {step===2?<label className="grid gap-2 text-sm font-bold">본문<textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={5000} className="min-h-64 rounded-xl border border-[#29465D] bg-[#050F19] p-4 leading-7" placeholder="20~5000자. 정확한 GPS, 집 주소, 개인 선박 계류 위치 공개를 피하세요."/></label>:null}
      {step===3?<div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-bold">시·도<input value={province} onChange={event=>setProvince(event.target.value)} maxLength={30} className="min-h-12 rounded-xl border border-[#29465D] bg-[#050F19] px-4"/></label><label className="grid gap-2 text-sm font-bold">시·군·구 (선택)<input value={district} onChange={event=>setDistrict(event.target.value)} maxLength={40} className="min-h-12 rounded-xl border border-[#29465D] bg-[#050F19] px-4"/></label><p className="sm:col-span-2 text-sm font-semibold leading-6 text-[#9FB3C8]">자유입력 GPS 필드는 제공하지 않습니다. 포인트 연결은 다음 단계에서 정확한 등록 ID를 직접 선택할 때만 생성됩니다.</p></div>:null}
      {step===4?<div><label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-full border border-[#79C9D6]/50 px-5 text-sm font-black"><ImagePlus size={18}/>사진 선택<input type="file" accept="image/jpeg,image/png,image/webp" multiple className="sr-only" onChange={event=>addImages(event.target.files)}/></label><p className="mt-3 text-sm text-[#9FB3C8]">JPEG·PNG·WebP, 장당 8 MiB, 최대 10장. 로컬 미리보기이며 업로드되지 않습니다.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">{images.map(image=><div key={image.id} className="overflow-hidden rounded-xl border border-[#29465D] bg-[#050F19]"><div className="aspect-square bg-cover bg-center" style={{backgroundImage:`url(${image.url})`}}/><div className="flex items-center gap-2 p-2"><span className="min-w-0 flex-1 truncate text-xs">{image.name}</span><button type="button" onClick={()=>removeImage(image.id)} aria-label={`${image.name} 삭제`} className="flex h-11 w-11 items-center justify-center"><Trash2 size={16}/></button></div></div>)}</div></div>:null}
      {step===5?picker("관련 어종", "species", catalog.species):null}
      {step===6?<div className="grid gap-5">{picker("관련 낚시 포인트", "fishingSpots", catalog.fishingSpots)}{picker("관련 출조", "charters", catalog.charters)}{picker("관련 마켓 판매글", "marketListings", catalog.marketListings)}</div>:null}
      {step===7?<div className="grid gap-3 sm:grid-cols-2">{[["유형",communityPostTypeLabels[type as keyof typeof communityPostTypeLabels]],["제목",title||"미입력"],["지역",`${province} ${district}`.trim()||"미입력"],["사진",`${images.length}장`],["어종 연결",`${links.species.length}개`],["기타 연결",`${links.fishingSpots.length+links.charters.length+links.marketListings.length}개`]].map(([label,value])=><div key={label} className="min-w-0 rounded-xl bg-[#0B2235] p-4"><p className="text-xs font-black text-[#79C9D6]">{label}</p><p className="mt-1 break-words text-sm font-bold">{value}</p></div>)}</div>:null}
      {step===8?<div><div className="flex gap-3 rounded-xl border border-amber-300/25 bg-amber-300/8 p-4 text-sm font-semibold leading-6 text-amber-50"><ShieldCheck className="mt-0.5 shrink-0" size={18}/><p>규칙 기반 검사는 검토 필요 표현을 표시할 뿐 법률·범죄·안전 판정을 자동으로 내리지 않습니다. 저장 상태는 SUBMITTED / REVIEW_REQUIRED입니다.</p></div><button type="button" onClick={submit} className="mt-4 min-h-12 w-full rounded-xl bg-[#2E8BFF] px-5 text-sm font-black">로컬 검토 대기로 저장</button></div>:null}
    </div>{errors.length?<ul className="mt-5 list-disc rounded-xl bg-rose-300/10 p-4 pl-9 text-sm text-rose-100">{errors.map(error=><li key={error}>{error}</li>)}</ul>:null}{warnings.length?<ul className="mt-4 list-disc rounded-xl bg-amber-300/8 p-4 pl-9 text-sm text-amber-50">{warnings.map(warning=><li key={warning}>{warning}</li>)}</ul>:null}{savedId?<div className="mt-5 rounded-xl border border-emerald-300/25 bg-emerald-300/8 p-4 text-sm font-semibold leading-6 text-emerald-50"><CheckCircle2 className="mr-2 inline" size={18}/><strong>로컬 검토 대기 저장됨</strong><br/>ID: <span className="break-all">{savedId}</span><br/>서버 제출 또는 운영 게시가 아닙니다.</div>:null}
    <div className="mt-7 flex justify-between gap-3"><button type="button" disabled={step===0} onClick={()=>setStep(value=>Math.max(0,value-1))} className="min-h-11 rounded-full border border-[#29465D] px-5 text-sm font-black disabled:opacity-30">이전</button><button type="button" disabled={step===steps.length-1} onClick={()=>setStep(value=>Math.min(steps.length-1,value+1))} className="min-h-11 rounded-full bg-[#123A57] px-5 text-sm font-black disabled:opacity-30">다음</button></div>
  </div></section>;
}
