const fs = require("node:fs");
const path = require("node:path");
const ts = require("typescript");
const Module = require("node:module");
const root = path.resolve(__dirname, "../../../..");
const cache = new Map();
function loadTs(relative) { const file = path.join(root, relative); if (cache.has(file)) return cache.get(file).exports; const output = ts.transpileModule(fs.readFileSync(file, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true } }).outputText; const mod = new Module(file, module); cache.set(file, mod); mod.filename = file; mod.paths = Module._nodeModulePaths(path.dirname(file)); const originalRequire = mod.require.bind(mod); mod.require = (request) => { if (request.startsWith(".")) { const base = path.resolve(path.dirname(file), request); if (fs.existsSync(`${base}.ts`)) return loadTs(path.relative(root, `${base}.ts`)); if (fs.existsSync(path.join(base, "index.ts"))) return loadTs(path.relative(root, path.join(base, "index.ts"))); } return originalRequire(request); }; mod._compile(output, file); return mod.exports; }
function createFixture(options = {}) { const { FishMediaGatewayService } = loadTs("src/domain/fish-observation/storage/application/fish-media-gateway-service.ts"); const { InMemoryFishMediaRepository } = loadTs("src/domain/fish-observation/storage/testing/in-memory-fish-media-repository.ts"); const { FakeFishStorageProvider } = loadTs("src/domain/fish-observation/storage/testing/fake-fish-storage-provider.ts"); const { FakeFishImageProcessor } = loadTs("src/domain/fish-observation/storage/testing/fake-fish-image-processor.ts"); const { InMemoryFishCleanupQueue } = loadTs("src/domain/fish-observation/storage/testing/in-memory-fish-cleanup-queue.ts"); const { FakeFishObservationAccess } = loadTs("src/domain/fish-observation/storage/testing/fake-fish-observation-access.ts"); const { InMemoryFishMediaAuditLog } = loadTs("src/domain/fish-observation/storage/testing/in-memory-fish-media-audit-log.ts"); const repository = new InMemoryFishMediaRepository(), storage = new FakeFishStorageProvider(), imageProcessor = new FakeFishImageProcessor(), cleanupQueue = new InMemoryFishCleanupQueue(), observationAccess = new FakeFishObservationAccess(), auditLog = new InMemoryFishMediaAuditLog(); observationAccess.observations.set("obs-1", { ownerUserId: "user-1", deletionStatus: "active", visibility: "public" }); let n = 0; return { repository, storage, imageProcessor, cleanupQueue, observationAccess, auditLog, service: new FishMediaGatewayService({ repository, storage, imageProcessor, cleanupQueue, observationAccess, auditLog, now: options.now ?? (() => new Date("2026-08-03T00:00:00.000Z")), createId: () => `id-${++n}` }) }; }
module.exports = { createFixture };
