const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const ts = require("typescript");
const Module = require("node:module");
const root = path.resolve(__dirname, "../../.."); const cache = new Map();
function load(relative) { const file = path.join(root, relative); if (cache.has(file)) return cache.get(file).exports; const out = ts.transpileModule(fs.readFileSync(file, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true } }).outputText; const mod = new Module(file, module); cache.set(file, mod); mod.filename = file; mod.paths = Module._nodeModulePaths(path.dirname(file)); const base = mod.require.bind(mod); mod.require = (request) => request.startsWith(".") ? load(path.relative(root, `${path.resolve(path.dirname(file), request)}.ts`)) : base(request); mod._compile(out, file); return mod.exports; }
const { FishRoleManagementService } = load("src/domain/fish-authorization/application/fish-role-management-service.ts");
const { FakeFishRoleAdminProvider } = load("src/domain/fish-authorization/testing/fake-fish-role-admin-provider.ts");
const { InMemoryFishRoleDirectory } = load("src/domain/fish-authorization/testing/in-memory-fish-role-directory.ts");
const { InMemoryFishRoleAuditRepository } = load("src/domain/fish-authorization/testing/in-memory-fish-role-audit-repository.ts");
const { InMemoryFishRoleIdempotencyRepository } = load("src/domain/fish-authorization/testing/in-memory-fish-role-idempotency-repository.ts");
const { FakeFishRoleSessionRevoker } = load("src/domain/fish-authorization/testing/fake-fish-role-session-revoker.ts");
const { FakeFishRoleApprovalVerifier } = load("src/domain/fish-authorization/testing/fake-fish-role-approval-verifier.ts");
const { FakeFishRoleClock } = load("src/domain/fish-authorization/testing/fake-fish-role-clock.ts");
function fixture(enabled = true) { const adminProvider = new FakeFishRoleAdminProvider(); const directory = new InMemoryFishRoleDirectory(); directory.users.set("admin", "human_user"); directory.users.set("reviewer", "human_user"); directory.users.set("crawler", "service_identity"); const auditRepository = new InMemoryFishRoleAuditRepository(); const sessionRevoker = new FakeFishRoleSessionRevoker(); return { adminProvider, directory, auditRepository, sessionRevoker, service: new FishRoleManagementService({ enabled, adminProvider, directory, auditRepository, idempotencyRepository: new InMemoryFishRoleIdempotencyRepository(), sessionRevoker, approvalVerifier: new FakeFishRoleApprovalVerifier(), clock: new FakeFishRoleClock() }) }; }
const actor = { actorUserId: "admin", actorFishRole: "fish_admin", requestId: "request-1" };
const grant = (more = {}) => ({ targetUserId: "reviewer", role: "fish_reviewer", reason: "Approved review operations", approvalReference: "APP-1", idempotencyKey: "idempotency-1", ...more });
const revoke = (more = {}) => ({ targetUserId: "reviewer", reason: "Review duty ended", approvalReference: "APP-2", idempotencyKey: "idempotency-2", ...more });
test("admin grants reviewer with an audit record and idempotent replay", async () => { const f = fixture(); const first = await f.service.grant(grant(), actor); const replay = await f.service.grant(grant(), actor); assert.equal(first.changed, true); assert.equal(replay.changed, true); assert.equal(f.adminProvider.roles.get("reviewer"), "fish_reviewer"); assert.equal(f.auditRepository.events.length, 1); assert.equal(Object.keys(f.auditRepository.events[0]).includes("approvalReference"), false); });
test("feature-disabled service fails closed before provider or directory access", async () => { const f = fixture(false); await assert.rejects(() => f.service.grant(grant(), actor), (error) => error && error.code === "FISH_ROLE_MANAGEMENT_DISABLED"); assert.equal(f.adminProvider.calls, 0); });
test("blocks self-admin elevation and human crawler grant", async () => { const f = fixture(); await assert.rejects(() => f.service.grant(grant({ targetUserId: "admin", role: "fish_admin", idempotencyKey: "idempotency-3" }), actor), /FISH_ROLE_SELF_ESCALATION_BLOCKED/); await assert.rejects(() => f.service.grant(grant({ role: "fish_crawler", idempotencyKey: "idempotency-4" }), actor), /FISH_ROLE_SERVICE_IDENTITY_REQUIRED/); const crawler = await f.service.grant(grant({ targetUserId: "crawler", role: "fish_crawler", idempotencyKey: "idempotency-5" }), actor); assert.equal(crawler.newRole, "fish_crawler"); });
test("revoke protects final admin and records pending session invalidation", async () => { const f = fixture(); f.adminProvider.roles.set("reviewer", "fish_reviewer"); f.sessionRevoker.fail = true; const result = await f.service.revoke(revoke(), actor); assert.equal(result.sessionRevocationStatus, "pending"); assert.match(result.warnings.join(" "), /ROLE_REVOCATION_PENDING_SESSION_INVALIDATION/); f.adminProvider.roles.set("reviewer", "fish_admin"); f.directory.activeAdmins = 1; await assert.rejects(() => f.service.revoke(revoke({ idempotencyKey: "idempotency-6" }), actor), /FISH_ROLE_LAST_ADMIN_PROTECTED/); });
test("idempotency conflicts and expired approvals are blocked", async () => { const f = fixture(); await f.service.grant(grant(), actor); await assert.rejects(() => f.service.grant(grant({ role: "fish_admin" }), actor), /FISH_ROLE_IDEMPOTENCY_CONFLICT/); const expired = fixture(); expired.service.deps; const verifier = new FakeFishRoleApprovalVerifier(); verifier.approval = { ...verifier.approval, expiresAt: "2020-01-01T00:00:00.000Z" }; const service = new FishRoleManagementService({ enabled: true, adminProvider: expired.adminProvider, directory: expired.directory, auditRepository: expired.auditRepository, idempotencyRepository: new InMemoryFishRoleIdempotencyRepository(), sessionRevoker: expired.sessionRevoker, approvalVerifier: verifier, clock: new FakeFishRoleClock() }); await assert.rejects(() => service.grant(grant({ idempotencyKey: "idempotency-7" }), actor), /FISH_ROLE_APPROVAL_EXPIRED/); });
